models.py
from . import db

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30))
    email = db.Column(db.String(120))
    comment_text = db.Column(db.String(1000))

__init__.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy 

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'

    db.init_app(app)

    from .views import main 
    app.register_blueprint(main)

    return app

views.py
from flask import Blueprint, render_template, request, redirect, url_for
from . import db
from .models import Comment

main = Blueprint('main', __name__)

@main.route('/')
def index():
    comments = Comment.query.all()
    return render_template('index.html', comments=comments)

@main.route('/sign')
def sign():
    return render_template('sign.html')

@main.route('/sign', methods=['POST'])
def sign_post():
    name = request.form.get('name')
    email = request.form.get('email')   
    comment = request.form.get('comment')

    new_comment = Comment(name=name, email=email, comment_text=comment)
    db.session.add(new_comment)
    db.session.commit()
    
    return redirect(url_for('main.index'))

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/learn')
def learn():
    return render_template('learn.html')

@main.route('/info')
def info():
    return render_template('info.html')

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block css %}
<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/sign.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}

<h1>Hello!</h1>

<div>
    My name is Isa.
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    
    <!-- <img src="/static/images/wolken.jpeg" alt="munich" class="center"> -->

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet"> 
    
    {% block css %}{% endblock %}

  </head>

  <body>
    {% block body %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}IsaLingua{% endblock %}

{% block css %}
<!-- Bootstrap theme -->
<!-- <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet"> -->

<!-- Custom styles for this template -->
<!-- <link href="{{ url_for('static', filename='css/theme.css') }}" rel="stylesheet"> -->
{% endblock %}

{% block body %}
<div class="container theme-showcase" role="main">

    <div class="jumbotron">
        <h1>IsaLingua</h1>
    </div>
    <div class="btn-toolbar" role="toolbar">
        <button type="button" class="btn btn-dark" onclick=window.location.href="{{ url_for('main.about') }}">About</button>
        <button type="button" class="btn btn-dark" onclick=window.location.href="{{ url_for('main.learn') }}">Learn</button>
        <button type="button" class="btn btn-dark" onclick=window.location.href="{{ url_for('main.info') }}">Info</button>
        <button type="button" class="btn btn-dark" onclick=window.location.href="{{ url_for('main.sign') }}">Comment</button>

    </div>

    {% for comment in comments %}
    <div class="page-header">
        <h1>{{ comment.name }}</h1>
        <div>
            {{ comment.email }}
            <button>&#10007;</button>
        </div>
    </div>
    <div class="well">
        <p>{{ comment.comment_text }}</p>
    </div>
    {% endfor %}

</div> <!-- /container -->
{% endblock %}

templates/info.html
{% extends 'base.html' %}

{% block title %}Info{% endblock %}

{% block css %}
<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/sign.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}

<div class="text-center">
    <h1>Info <small>Get started and get more information.</small></h1>
</div>

<form class="form-horizontal d-flex justify-content-center">
    <div class="form-group">
        <label class="col-xs-2 control-label">First Name</label>
        <div class="col-xs-5">
            <input type="text" class="form-control" id="fname" placeholder="First Name">
        </div>
    </div>

    <div class="form-group">
        <label for="pwd" class="col-xs-2 control-label">Last Name</label>
        <div class="col-xs-5">
            <input type="text" class="form-control" id="lname" placeholder="Last Name">
        </div>
    </div>

    <div class="form-group">
        <label for="pwd" class="col-xs-2 control-label">E-mail</label>
        <div class="col-xs-5">
            <input type="text" class="form-control" id="lname" placeholder="E-mail">
        </div>
    </div>

    <div class="form-group">
        <label for="pwd" class="col-xs-2 control-label">Age</label>
        <div class="col-xs-5">
            <input type="text" class="form-control" id="lname" placeholder="Age">
        </div>
    </div>

    <fieldset class="form-group">
        <div class="">
            <legend class="col-form-label col-sm-2 pt-0">Level</legend>
            <div class="col-sm-10">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
                    <label class="form-check-label" for="gridRadios1">
                    A1 - A2
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
                    <label class="form-check-label" for="gridRadios2">
                    B1 - B2
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
                    <label class="form-check-label" for="gridRadios2">
                    C1 - c2
                    </label>
                </div>
            </div>
        </div>
    </fieldset>

</form>


{% endblock %}

templates/learn.html
{% extends 'base.html' %}

{% block title %}Learn{% endblock %}

{% block css %}
<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/sign.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}

<h1>Hello!</h1>

<div>
    This is a test.
</div>

{% endblock %}

templates/sign.html
{% extends 'base.html' %}

{% block title %}Info{% endblock %}

{% block css %}
<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/sign.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}

<div class="bg"></div>

<div class="container">

    <form class="form-signin" method="POST" action="{{ url_for('main.sign_post') }}">
        <h2 class="form-signin-heading">Leave me a comment</h2>
        <div class="form-group">
            <label for="inputName" class="sr-only">Name</label>
            <input type="text" id="inputName" name="name" class="form-control" placeholder="Name" required autofocus>
        </div>
        <div class="form-group">
            <label for="inputMail" class="sr-only">E-mail</label>
            <input type="text" id="inputMail" name="email" class="form-control" placeholder="E-mail" required autofocus>
        </div>
        <div class="form-group">
            <label for="comment" class="sr-only">Comment:</label>
            <textarea class="form-control" name="comment" rows="5" id="comment" placeholder="Comment"
                required></textarea>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign</button>
    </form>

</div> <!-- /container -->
{% endblock %}